sudo: required
services:
  - docker

before_install:
  - docker build -t ivanac/docker-react-u -f Dockerfile.dev .

script:
  - docker run -e CI=true ivanac/docker-react-u npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-u"
  env: "DockerReactU-env"
  bucket_name: "elasticbeanstalk-us-west-2-193222755118"
  bucket_path: "docker-react-u"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
